### ISSUE TITLE
Diffs have incorrect node names when using namespaces

### ISSUE THREAD

**Issue by joedj** [Shoobx/xmldiff#21]
Hiya,

Thanks for working on this lib!  I've found that when namespaces are in use, the node paths in diffs aren't so great.

Tested with 2.0b7.

```python
#!/usr/bin/env python

import xmldiff.main
import unittest

class Test(unittest.TestCase):

    def testWithoutNamespace(self):
        old = '<tag>old</tag>'
        new = '<tag>new</tag>'
        diff = xmldiff.main.diff_texts(old, new)
        self.assertEquals(len(diff), 1)
        self.assertEquals(diff[0].node, '/tag[1]')

    def testWithNamespace(self):
        old = '<tag xmlns="ns">old</tag>'
        new = '<tag xmlns="ns">new</tag>'
        diff = xmldiff.main.diff_texts(old, new)
        self.assertEquals(len(diff), 1)
        self.assertEquals(diff[0].node, '/tag[1]')

if __name__ == '__main__':
    unittest.main()
```

Output:
```
⇒  ./test_namespace.py
F.
======================================================================
FAIL: testWithNamespace (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_namespace.py", line 20, in testWithNamespace
    self.assertEquals(diff[0].node, '/tag[1]')
AssertionError: '/*[1]' != '/tag[1]'

----------------------------------------------------------------------
Ran 2 tests in 0.006s

FAILED (failures=1)
```

**Comment by regebro** [comment]
Interesting, I'll check.

**Comment by regebro** [comment]
The XPath given is of course valid, but not very human readable. So I've dug around, and this actually comes down to a bit from libxml2, which is the C library that lxml uses. 

> We cannot express named elements in the default namespace, so use "*".

https://github.com/tenderlove/libxml2/blob/master/tree.c#L4593

So this happens when you are using a default namespace. 

I thought they could just use the tag when you had a default namespace, but it seems not. I suspect it will be hard to do anything about this except for having a completely custom getpath() function, which will slow things down a lot, just to get more readable diffs. One option could maybe be to remove any default namespace before diffing?

**Comment by joedj** [comment]
I see.  Yeah, that's what I'm doing at the moment for all/most namespaces, using some regex kludges.  Broken I'm sure, but works for my use-cases so far:

```python
def strip_namespaces(xml):
    xml = re.sub(r'\s*xmlns[:\w]*="[^"]*"', '', xml)
    xml = re.sub('<[:\w]+:', '<', xml)
    xml = re.sub('</[:\w]+:', '</', xml)
    return xml
```

**Comment by regebro** [comment]
Yeah, that seems reasonable. I looked at stripping default namespaces with lxml, but that requires you to traverse the whole tree, which isn't an effective solution compared with removing the declarations.

It's only the default namespace that has this effect, though, so you can probably simplify it.

**Comment by strichter** [comment]
@regebro I think we can safely close this issue, since there is not much we can do and we are not producing an incorrect result.
