### ISSUE TITLE
comparison of two xml files

### ISSUE THREAD

**Issue by damon-atkins** [Shoobx/xmldiff#44]
What is the best way to get a human readable comparison of two large xml files. Maybe a bit like sdiff side by side comparison. So its easy to compare/review. or xpath vs xpath value
File 1
```
<note>
    <msg>Hi</msg>
    <to important=true>Jim</to>
</note>
```
File 2
```
<note>
    <to important=false>James</to> 
    <msg>Hi</msg>
</note>
```
Example Results
Show all, what I am missing is sdiff char which indicates what sort of difference it is.
```
File1                             File2
<note>                            <note>
    <msg>Hi</msg>                     <msg>Hi</msg>
    <to important=true>Jim</to>       <to important=false>James</to>
</note>                           </note>
```
OR Show only diffs, handling unordered structures
```
File1                             File2               
<note>
    <msg>Hi</msg>
    <to important=true>Jim</to>       <to important=false>James</to>
</note>
```

**Comment by regebro** [comment]
If you want an sdiff type comparison, the best you can do is to use sdiff. You probably need to normalize the XML first so you don't get shown mostly formatting changes. The best way to normalize the files are dependent on your XML, since your XML files don't care about order, for example. 

With xmldiff you can't get line by line comparisons, because XML isn't a line by line format.
