### ISSUE TITLE
XMLFormatter fails to append a newline "Element" sometimes

### ISSUE THREAD

**Issue by juliankrieger** [Shoobx/xmldiff#51]
Consider following input

```<?xml version="1.0" encoding="ISO-8859-1"?>
<note>
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<note>
  <to>Tove</to>
  <from>Alex</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

And the following minimal python code

```
if __name__ == '__main__':

    formatter = formatting.XMLFormatter(
        pretty_print=True,
        text_tags=(
            'to'
        )
    )
    res = main.diff_files(
        "example.xml",
        "example_diff.xml",
        formatter=formatter,
        diff_options={
            'ratio_mode': 'accurate'
        }
    )

    print(res)
```

XMLDiff will print the following Output

```
<note xmlns:diff="http://namespaces.shoobx.com/diff">
  <to>Tove</to>
  <from diff:insert="">Alex</from><diff:insert>
  </diff:insert><from diff:delete="">Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

As you can see, between the `from`tag and the `diff:insert`tag, there is a missing newline

**Comment by juliankrieger** [comment]
I have found out why the issue occurs, but I am not sure how to fix it.

**Comment by juliankrieger** [comment]
As such, I suggest the following fix:

```
if element is None or len(result.getchildren()) > 1:
            return result
        else:
            return element
```

**Comment by regebro** [comment]
No, that newline isn't missing. If it inserted a newline there, there would have two newlines between the from tag and heading tag.

What I am surprised about is that it inserts the newline + spaces text after the new from-line. I'll have to look into that. I would expect this output:
 
```
<note xmlns:diff="http://namespaces.shoobx.com/diff">
  <to>Tove</to>
  <from diff:insert="">Alex</from><from diff:delete="">Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

**Comment by regebro** [comment]
Update: I know why, I just haven't figure out what the solution for it is.

**Comment by regebro** [comment]
To recap my findings.

So, it looks strange, but it's in itself correct. When the node gets deleted, the spaces after the node (the tail) will also get deleted. So the inserted node must have a new tail, and that's what is added. So we get three actions in the diff: 1. Insert a new node, 2. update the text, 3. update the tail, 4. remove the old node.

There might be a nicer way of doing this, but I can't come up with anything right now. 

However, it ends up looking strange in the XML formatting, since it's not obvious that the newline after the from-tag will be deleted if this patch is applied. Passing in the WS_BOTH normalizing setting makes for a nicer output, but it also does make it look like there will be an empty line in there.

```
from xmldiff import formatting, main

if __name__ == '__main__':

    formatter = formatting.XMLFormatter(
        pretty_print=True,
        normalize=formatting.WS_BOTH,
        text_tags=(
            'to'
        )
    )
    res = main.diff_files(
        "left.xml",
        "right.xml",
        formatter=formatter,
        diff_options={
            'ratio_mode': 'accurate'
        }
    )

    print(res)
```
